################################################################################
################################################################################
##                                                                            ##
##                     BungeeIPC Configuration for Bukkit                     ##
##                                                                            ##
## SOURCE CODE: https://github.com/bspfsystems/BungeeIPC/                     ##
## BUGS / ISSUES: https://github.com/bspfsystems/BungeeIPC/issues/            ##
## API JAVADOCS: https://bspfsystems.org/docs/bungeeipc/                      ##
##                                                                            ##
## New configuration items will not be added to this file automatically. You  ##
## can obtain an updated version of the default config.yml file from          ##
## https://bspfsystems.org/config-files/bungeeipc/bukkit/                     ##
##                                                                            ##
## This file may also be named "bukkitipc.yml". If both "bukkitipc.yml" and   ##
## "config.yml" are present in this plugin's configuration directory,         ##
## the "bukkitipc.yml" file will be preferred over the "config.yml" file.     ##
##                                                                            ##
## IMPORTANT: Please take note of which settings (SSL/TLS settings) should be ##
##            mirrored in the Bungee plugin's configuration file, as the      ##
##            connection is likely to fail if they are not mirrored.          ##
##                                                                            ##
## For more information on configuring the Bukkit plugin for BungeeIPC,       ##
## including each individual configuration option in this file, please see    ##
## the configuration documentation at                                         ##
## https://bspfsystems.org/config-docs/bungeeipc/, under the section named    ##
## "Bukkit Configuration Options".                                            ##
##                                                                            ##
################################################################################
################################################################################

################################################################################
#                           General Plugin Settings                            #
################################################################################

# The logging level for the plugin logger.
# - The default value is "INFO".
logging_level: "INFO"

################################################################################
#                           IPC Client Configuration                           #
################################################################################

# The hostname or IP address of the BungeeCord server
# - If no hostname or IP address is specified, "localhost" will be used
#   (127.0.0.1).
bungeecord_ip: ""

# The port to connect to on the BungeeCord server
# - If no port number is specified, or -1 is specified (the default), then an
#   exception will be thrown.
port: -1

################################################################################
#                           Global SSL/TLS Settings                            #
#                                                                              #
# IMPORTANT: Please take note of which settings should be mirrored in the      #
#            BungeeCord plugin's configuration file, as the connection is      #
#            likely to fail if they are not mirrored.                          #
################################################################################

# Whether to use SSL/TLS or not
# - MUST BE MIRRORED.
# - DISCLAIMER: While it is much easier to not use SSL/TLS, this should be
#               restricted to a testing environment. Even if the BungeeCord
#               proxy and the Minecraft server(s) run on the same machine, it is
#               best-practice to use encryption while data is in transit, no
#               matter how "unimportant" the data is.
# - Please note that while the label would indicate using SSL, which has been
#   superseded by TLS, this setting is to enable using SSL/TLS.
use_ssl: false

################################################################################
#                            Basic SSL/TLS settings                            #
#              These will be ignored if use_ssl is set to "false"              #
################################################################################

# The SSLContext protocol
# - Highly recommended to be mirrored.
# - If no protocol is specified, "TLS" will be used.
ssl_context_protocol: "TLS"

# The TLS versions
# - Highly recommended to be mirrored.
# - If this list is null or empty, only TLSv1.2 will be whitelisted.
tls_version_whitelist:
  - "TLSv1.2"

# The Cipher Suites
# - Highly recommended to be mirrored.
# - If this list is null or empty, the following cipher suites will be used by
#   default:
#   - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
tls_cipher_suite_whitelist:
  - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
