################################################################################
################################################################################
##                             BungeeIPC for Bukkit                           ##
##                                                                            ##
## SOURCE CODE: https://github.com/bspfsystems/BungeeIPC/                     ##
## BUGS / ISSUES: https://github.com/bspfsystems/BungeeIPC/issues/            ##
## API JAVADOCS: https://javadoc.io/doc/org.bspfsystems/<something>           ##
##                                                                            ##
## New configuration items will not be added to this file automatically. You  ##
## can obtain an updated version of the default config.yml file from          ##
## https://bspfsystems.org/config-files/bungeeipc/bukkit/                     ##
##                                                                            ##
## IMPORTANT NOTE: The below settings must be mirrored in the BungeeCord      ##
##                 plugin's configuration, otherwise the connection has a     ##
##                 good chance of failing.                                    ##
################################################################################
################################################################################

################################################################################
#                           Global SSL/TLS Settings                            #
################################################################################

# Whether to use SSL/TLS or not
#
# DISCLAIMER: While it is much easier to not use SSL/TLS, this should be
#             restricted to a testing environment. Even if the BungeeCord proxy
#             and the Minecraft server(s) run on the same machine, it is
#             best-practice to use encryption while data is in transit, no
#             matter how "unimportant" the data is.
# Please note that while the label would indicate using SSL, which has been
# superseded by TLS, the default is to use TLS v1.2.
use_ssl: false

################################################################################
#                            Basic SSL/TLS settings                            #
#               These can be ignored if use_ssl is set to false                #
################################################################################

# The SSLContext protocol
#
# - It is recommended to use the latest version of SSL/TLS that your system
#   supports.
# - If no protocol is specified, "TLS" will be used.
ssl_context_protocol: "TLS"

# The TLS versions
#
# - The list of TLS versions that you wish to be able to use.
# - This is separate from the item above in that the above will allow all TLS
#   versions, but this is a whitelist of which versions are actually able to be
#   used.
# - If this list is null or empty, only TLSv1.2 will be whitelisted.
tls_version_whitelist:
  - "TLSv1.2"

# The Cipher Suites
#
# - The list of Cipher Suites that are whitelisted for use with the SSLSockets.
# - There are over 40 that the SSLSocket(s) will use by default, some of which
#   are less-than-ideal to use. The following list whitelists the ones that
#   should be used for BungeeIPC.
# - If this list is null or empty, the following cipher suites will be used by
#   default:
#   - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
tls_cipher_suite_whitelist:
  - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"