################################################################################
################################################################################
##                           BungeeIPC for BungeeCord                         ##
##                                                                            ##
## SOURCE CODE: https://github.com/bspfsystems/BungeeIPC/                     ##
## BUGS / ISSUES: https://github.com/bspfsystems/BungeeIPC/issues/            ##
## API JAVADOCS: https://javadoc.io/doc/org.bspfsystems/<something>           ##
##                                                                            ##
## New configuration items will not be added to this file automatically. You  ##
## can obtain an updated version of the default config.yml file from          ##
## <link>.                                                                    ##
################################################################################
################################################################################

################################################################################
#                           Global SSL/TLS Settings                            #
################################################################################

# Whether to use SSL/TLS or not
#
# DISCLAIMER: While it is much easier to not use SSL/TLS, this should be
#             restricted to a testing environment. Even if the BungeeCord proxy
#             and the Minecraft server(s) run on the same machine, it is
#             best-practice to use encryption while data is in transit, no
#             matter how "unimportant" the data is.
use_ssl: false

################################################################################
#                            Basic SSL/TLS settings                            #
#               These can be ignored if use_ssl is set to false                #
################################################################################

# The KeyStore file location
#
# - It is highly recommended to use the fully-qualified path to the KeyStore file.
# - If no file path is specified, an exception will be thrown.
key_store_file: ""

# The KeyStore password
#
# - It is highly recommended not to use a blank password.
# - If no password is specified, an exception will be thrown.
key_store_password: ""

# The SSLContext protocol
#
# - It is recommended to use the latest version of SSL/TLS that your system
#   supports.
# - If no protocol is specified, "TLS" will be used.
ssl_context_protocol: "TLS"

# The TLS versions
#
# - The list of TLS versions that you wish to be able to use.
# - This is separate from the item above in that the above will allow all TLS
#   versions, but this is a whitelist of which versions are actually able to be
#   used.
# - If this list is null or empty, TLSv1.1 and TLSv1.2 will be whitelisted.
tls_version_whitelist:
  - "TLSv1.1"
  - "TLSv1.2"

# The Cipher Suites
#
# - The list of Cipher Suites that are whitelisted for use with the SSLSockets.
# - There are over 40 that the SSLSocket(s) will use by default, some of which
#   are less-than-ideal to use. The following list whitelists the ones that
#   should be used for BungeeIPC.
# - If this list is null or empty, the following cipher suites will be used by
#   default:
#   - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256"
#   - "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256"
#   - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
#   - "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"
tls_cipher_suite_whitelist:
  - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256"
  - "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256"
  - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
  - "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"

################################################################################
#                          Advanced SSL/TLS settings                           #
#               These can be ignored if use_ssl is set to false                #
#                                                                              #
#                                   NOTICE:                                    #
#                     UNLESS YOU KNOW WHAT YOU ARE DOING,                      #
#                  IT IS BEST TO LEAVE THESE SETTINGS ALONE.                   #
################################################################################

# The KeyStore instance
#
# - Which instance of the KeyStore you want to use.
# - If no instance is specified, "JKS" will be used.
key_store_instance: "JKS"

# The KeyManagerFactory algorithm
#
# - The algorithm of the KeyManagerFactory you wish to use.
# - If no algorithm is specified, "NewSunX509" will be used.
key_manager_factory_algorithm: "NewSunX509"

# The TrustManagerFactory algorithm
#
# - The algorithm of the TrustManagerFactory you wish to use.
# - If no algorithm is specified, "NewSunX509" will be used.
trust_manager_factory_algorithm: "NewSunX509"