################################################################################
################################################################################
##                                                                            ##
##                   BungeeIPC Configuration for BungeeCord                   ##
##                                                                            ##
## SOURCE CODE: https://github.com/bspfsystems/BungeeIPC/                     ##
## BUGS / ISSUES: https://github.com/bspfsystems/BungeeIPC/issues/            ##
## API JAVADOCS: https://bspfsystems.org/docs/bungeeipc/                      ##
##                                                                            ##
## New configuration items will not be added to this file automatically. You  ##
## can obtain an updated version of the default config.yml file from          ##
## https://bspfsystems.org/config-files/bungeeipc/bungeecord/                 ##
##                                                                            ##
## This file may also be named "bungeeipc.yml". If both "bungeeipc.yml" and   ##
## "config.yml" are present in this plugin's configuration directory,         ##
## the "bungeeipc.yml" file will be preferred over the "config.yml" file.     ##
##                                                                            ##
## IMPORTANT: Please take note of which settings (SSL/TLS settings) should be ##
##            mirrored in the Bukkit plugin's configuration file, as the      ##
##            connection is likely to fail if they are not mirrored.          ##
##                                                                            ##
################################################################################
################################################################################

################################################################################
#                           General Plugin Settings                            #
################################################################################

# Enables extra logging for the plugin logger.
#
# - This is equivalent to a logging level of "debug".
# - Due to a limitation of BungeeCord's Logger, debug/config is not and cannot
#   be enabled. The alternative is to enable extra logging, which will come
#   across at the INFO level.
# - No settings will need to be changed in BungeeCord's config.yml file.
# - The default for this setting is false. Null or empty values will be treated
#   as false.
extra_logging: false

################################################################################
#                          IPC Servers Configuration                           #
################################################################################

# Section to define the IPC Servers
#
# - This section is where the IPCServers are configured, including server names,
#   hostnames/IP addresses, and ports.
# - The minimum information required for a server is the name of the server and
#   the port that it will bind to. Optionally, you may also include the hostname
#   or IP address that the specific server is to bind to (IP address is
#   preferred for binding).
# - The server names MUST match one of the server names configured in
#   BungeeCord's config.yml (or bungee.yml) configuration file.
# - If no hostname or IP address is supplied, "localhost" (or 127.0.0.1) will be
#   used.
# - If a hostname/IP address is specified, it does not have to be the same one
#   that players use to connect to BungeeCord. Depending on how you implement
#   your BungeeCord network, you may have a public IP that is used for players
#   to connect to, and then private IP address(es) and networking for the
#   connections from BungeeCord to the backend Minecraft servers.
# - If no port is specified, an error will be presented when this configuration
#   file is loaded, and the respective IPC Server will not start.
# - Port numbers must be between 1024 and 65535 (inclusive). Failure to abide by
#   this will result in an error and the respective IPC Server will not start.
# - The IP address and port combination that is specified for a server must not
#   match the connection information that players use to connect to BungeeCord,
#   nor can it match any other combination of other IPC Servers. The IP address
#   may be the same for all, but the ports must all be different for any cases
#   where the IP address is the same.
#
# - Example server configuration:
#
#   servers:
#     testserver1:
#       bind_address: 127.0.0.1
#       bind_port: 12345
#     testserver2:
#       bind_port: 55555
servers:

################################################################################
#                           Global SSL/TLS Settings                            #
################################################################################

# Whether to use SSL/TLS or not
#
# - MUST BE MIRRORED.
# - DISCLAIMER: While it is much easier to not use SSL/TLS, this should be
#               restricted to a testing environment. Even if the BungeeCord
#               proxy and the Minecraft server(s) run on the same machine, it is
#               best-practice to use encryption while data is in transit, no
#               matter how "unimportant" the data is.
# - Please note that while the label would indicate using SSL, which has been
#   superseded by TLS, this setting is to enable using SSL/TLS.
use_ssl: false

################################################################################
#                            Basic SSL/TLS Settings                            #
#              These will be ignored if use_ssl is set to "false"              #
################################################################################

# The KeyStore file location
#
# - It is highly recommended to use the fully-qualified path to the KeyStore file.
# - If no file path is specified, an exception will be thrown.
key_store_file: ""

# The KeyStore password
#
# - It is highly recommended not to use a blank password.
# - If no password is specified, an exception will be thrown.
key_store_password: ""

# The SSLContext protocol
#
# - Highly recommended to be mirrored. If not, the side that has the lower
#   protocol version as its "best" will determine the protocol version that will
#   be used ("as strong as the weakest link in the chain" analogy).
# - It is recommended to use the latest version of SSL/TLS that your system
#   supports.
# - If no protocol is specified, "TLS" will be used.
ssl_context_protocol: "TLS"

# The TLS versions
#
# - Highly recommended to be mirrored. If not, the side that has the lower
#   protocol version as its "best" will determine the protocol version that will
#   be used ("as strong as the weakest link in the chain" analogy).
# - The list of TLS versions that you wish to be able to use.
# - This is separate from the item above in that the above will allow all TLS
#   versions, but this is a whitelist of which versions are actually able to be
#   used.
# - If this list is null or empty, only TLSv1.2 will be whitelisted.
tls_version_whitelist:
  - "TLSv1.2"

# The Cipher Suites
#
# - Highly recommended to be mirrored. If not, the side that has the weaker
#   cipher suite as its "best" will determine the cipher suite that will be used
#   ("as strong as the weakest link in the chain" analogy).
# - The list of Cipher Suites that are whitelisted for use with the SSLSockets.
# - There are over 40 that the SSLSocket(s) will use by default, some of which
#   are less-than-ideal to use. The following list whitelists the ones that
#   should be used for BungeeIPC.
# - If this list is null or empty, the following cipher suites will be used by
#   default:
#   - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
tls_cipher_suite_whitelist:
  - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"

################################################################################
#                          Advanced SSL/TLS Settings                           #
#              These can be ignored if use_ssl is set to "false"               #
#                                                                              #
#                                   NOTICE:                                    #
#                     UNLESS YOU KNOW WHAT YOU ARE DOING,                      #
#                  IT IS BEST TO LEAVE THESE SETTINGS ALONE.                   #
################################################################################

# The KeyStore instance
#
# - Which instance of the KeyStore you want to use.
# - If no instance is specified, "JKS" will be used.
key_store_instance: "JKS"

# The KeyManagerFactory algorithm
#
# - The algorithm of the KeyManagerFactory you wish to use.
# - If no algorithm is specified, "NewSunX509" will be used.
key_manager_factory_algorithm: "NewSunX509"

# The TrustManagerFactory algorithm
#
# - The algorithm of the TrustManagerFactory you wish to use.
# - If no algorithm is specified, "SunX509" will be used.
trust_manager_factory_algorithm: "SunX509"
