################################################################################
################################################################################
##                                                                            ##
##                   BungeeIPC Configuration for BungeeCord                   ##
##                                                                            ##
## SOURCE CODE: https://github.com/bspfsystems/BungeeIPC/                     ##
## BUGS / ISSUES: https://github.com/bspfsystems/BungeeIPC/issues/            ##
## API JAVADOCS: https://bspfsystems.org/docs/bungeeipc/                      ##
##                                                                            ##
## New configuration items will not be added to this file automatically. You  ##
## can obtain an updated version of the default config.yml file from          ##
## https://bspfsystems.org/config-files/bungeeipc/bungeecord/                 ##
##                                                                            ##
## This file may also be named "bungeeipc.yml". If both "bungeeipc.yml" and   ##
## "config.yml" are present in this plugin's configuration directory,         ##
## the "bungeeipc.yml" file will be preferred over the "config.yml" file.     ##
##                                                                            ##
## IMPORTANT: Please take note of which settings (SSL/TLS settings) should be ##
##            mirrored in the Bukkit plugin's configuration file, as the      ##
##            connection is likely to fail if they are not mirrored.          ##
##                                                                            ##
## For more information on configuring the BungeeCord plugin for BungeeIPC,   ##
## including each individual configuration option in this file, please see    ##
## the configuration documentation at                                         ##
## https://bspfsystems.org/config-docs/bungeeipc/, under the section named    ##
## "BungeeCord Configuration Options".                                        ##
##                                                                            ##
################################################################################
################################################################################

################################################################################
#                           General Plugin Settings                            #
################################################################################

# The logging level for the plugin logger.
# - The default value is "INFO".
logging_level: "INFO"

################################################################################
#                          IPC Servers Configuration                           #
################################################################################

# Section to define the IPC Servers
# - Example server configuration:
#
#   servers:
#     testserver1:
#       bind_address: 127.0.0.1
#       bind_port: 12345
#     testserver2:
#       bind_port: 55555
servers:

################################################################################
#                           Global SSL/TLS Settings                            #
################################################################################

# Whether to use SSL/TLS or not
# - MUST BE MIRRORED.
# - DISCLAIMER: While it is much easier to not use SSL/TLS, this should be
#               restricted to a testing environment. Even if the BungeeCord
#               proxy and the Minecraft server(s) run on the same machine, it is
#               best-practice to use encryption while data is in transit, no
#               matter how "unimportant" the data is.
# - Please note that while the label would indicate using SSL, which has been
#   superseded by TLS, this setting is to enable using SSL/TLS.
use_ssl: false

################################################################################
#                            Basic SSL/TLS Settings                            #
#              These will be ignored if use_ssl is set to "false"              #
################################################################################

# The KeyStore file location
# - If no file path is specified, an exception will be thrown.
key_store_file: ""

# The KeyStore password
# - If no password is specified, an exception will be thrown.
key_store_password: ""

# The SSLContext protocol
# - Highly recommended to be mirrored.
# - If no protocol is specified, "TLS" will be used.
ssl_context_protocol: "TLS"

# The TLS versions
# - Highly recommended to be mirrored.
# - If this list is null or empty, only TLSv1.2 will be whitelisted.
tls_version_whitelist:
  - "TLSv1.2"

# The Cipher Suites
# - Highly recommended to be mirrored.
# - If this list is null or empty, the following cipher suites will be used by
#   default:
#   - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
tls_cipher_suite_whitelist:
  - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"

################################################################################
#                          Advanced SSL/TLS Settings                           #
#              These can be ignored if use_ssl is set to "false"               #
#                                                                              #
#                                   NOTICE:                                    #
#                     UNLESS YOU KNOW WHAT YOU ARE DOING,                      #
#                  IT IS BEST TO LEAVE THESE SETTINGS ALONE.                   #
################################################################################

# The KeyStore instance
# - If no instance is specified, "PKCS12" will be used.
key_store_instance: "PKCS12"

# The KeyManagerFactory algorithm
# - If no algorithm is specified, "NewSunX509" will be used.
key_manager_factory_algorithm: "NewSunX509"

# The TrustManagerFactory algorithm
# - If no algorithm is specified, "SunX509" will be used.
trust_manager_factory_algorithm: "SunX509"
